//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animation()
        {
            this.AnimationPhoto = new HashSet<AnimationPhoto>();
            this.AnimationCategory = new HashSet<AnimationCategory>();
            this.EComment = new HashSet<EComment>();
            this.ECommentReply = new HashSet<ECommentReply>();
            this.ShortComment = new HashSet<ShortComment>();
            this.UserLikeA = new HashSet<UserLikeA>();
        }
    
        public int Animationid { get; set; }
        public string Aname { get; set; }
        public string AimagePic { get; set; }
        public string Adirector { get; set; }
        public string Awriter { get; set; }
        public string Amainactor { get; set; }
        public string Aweb { get; set; }
        public string Alocation { get; set; }
        public string Alanguage { get; set; }
        public string Adate { get; set; }
        public string Asetnumber { get; set; }
        public string AsetTime { get; set; }
        public string Anickname { get; set; }
        public string Aplot { get; set; }
        public Nullable<double> Score { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimationPhoto> AnimationPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimationCategory> AnimationCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EComment> EComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECommentReply> ECommentReply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShortComment> ShortComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLikeA> UserLikeA { get; set; }
    }
}
