//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dongtaiComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dongtaiComment()
        {
            this.dongtaiCommentlike = new HashSet<dongtaiCommentlike>();
            this.dongtaiCommentReply = new HashSet<dongtaiCommentReply>();
        }
    
        public int dongtaiCommentid { get; set; }
        public int dongtaiid { get; set; }
        public string UserName { get; set; }
        public string Content { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> Likenum { get; set; }
    
        public virtual dongtai dongtai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dongtaiCommentlike> dongtaiCommentlike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dongtaiCommentReply> dongtaiCommentReply { get; set; }
        public virtual Users Users { get; set; }
    }
}
