//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublishEvaluation
    {
        public int Publishid { get; set; }
        public string Aname { get; set; }
        public string Publishname { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<double> Score { get; set; }
        public string Result { get; set; }
        public string Reply { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
