//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempRankingList
    {
        public int Animationid { get; set; }
        public string Aname { get; set; }
        public string AimagePic { get; set; }
        public string Adirector { get; set; }
        public string Awriter { get; set; }
        public string Amainactor { get; set; }
        public string Aweb { get; set; }
        public string Alocation { get; set; }
        public string Alanguage { get; set; }
        public string Adate { get; set; }
        public string Asetnumber { get; set; }
        public string AsetTime { get; set; }
        public string Anickname { get; set; }
        public string Aplot { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<long> RowNum { get; set; }
    }
}
